_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": epoch/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/val_accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "3":
                - 2
                - 7
                - 15
                - 16
                - 38
                - 55
            "4": 3.11.9
            "5": 0.20.1
            "8":
                - 1
                - 2
                - 3
            "12": 0.20.1
            "13": windows-amd64
dropout_rate:
    value: 0.1
embed_dim:
    value: 512
ffn_dim:
    value: 256
loss:
    value: binary_crossentropy
num_classes:
    value: 1
optimizer:
    value: adam
