_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "3":
                - 2
                - 15
                - 16
                - 55
            "4": 3.11.9
            "5": 0.20.1
            "8":
                - 1
                - 2
                - 3
            "12": 0.20.1
            "13": windows-amd64
dropout_rate:
    value: 0.1
embed_dim:
    value: 512
loss:
    value: binary_crossentropy
num_classes:
    value: 1
optimizer:
    value: adam
